### ISSUE TITLE
Automatic saving and restoring does not work

### ISSUE THREAD

**Issue by zoidy** [manutalcual/winredock#11]
It seems that the [automatic saving and restoring](https://github.com/manutalcual/winredock/issues/5#issuecomment-441060685) does not work. The logging binary from issue #10 does seem to work except some windows maximized become unmaximized (can't consistently reproduce). 

Also, where is the config file saved now?

**Comment by aronovgj** [comment]
C:\Users\<username>\window_list.json

Your issue sounds like https://github.com/manutalcual/winredock/issues/8

**Comment by manutalcual** [comment]
Yep!
This is because for that binary, I'm doing several things at the same time to try to fix it for @aronovgj .
To be able to redistribute the windows, I have to: unmaximize, reposition and maximize again. I'm doing that, but there are two messages that trigger the repositioning: undock & redock and resolution change, and I think they are conflicting (there may be even two resolution change messages conflicting.) I think while the resolution change unmaximizes windows, their position are stored (saved in memory) and then restored... to their unmaximized position.
I'm trying to solve this. For me and some other people, the screen resolution changes when the laptop is docked or undocked; for some other people it is not: I have to discover _why_ the app works in previous versions and apply that to the last one.

**Comment by zoidy** [comment]
> `C:\Users\<username>\window_list.json`

Nope, it's not there or in the application folder

**Comment by manutalcual** [comment]
The file should be there. May be you don't have permissions to write into that directory?
Also you have o select "Save config." menu option. The saving of this version I'm talking about is the saving of window positions _in memory_ (not creating the file.)

(Just in case, you have to substitute <username> with the user name the app is currently being run with. It should be pretty obvious but some non technical users may use that literally and I don't know you knowledge.)

**Comment by zoidy** [comment]
> the saving of this version I'm talking about is the saving of window positions _in memory_ (not creating the file.)

Ah, I didn't realize the logging binary saved things in memory now
