### ISSUE TITLE
Maximized window isn't moved back

### ISSUE THREAD

**Issue by zoidy** [manutalcual/winredock#2]
Hi, thanks for the tool! It seems that maximized windows aren't moved back unless they are un-maximized first.

1. Move window to secondary monitor and maximize it
2. Save config
3. Undock my laptop and re-dock it. At this point, all windows are moved to primary monitor. The maximized window remains maximized.
4. Restore config.

Expected behavior: all windows are moved back to where they were saved
Actual behavior: Non-maximized windows are moved back. The maximized window is not. If I un-maximize and click Restore config, the window moves to where it was at step 2 above. 

OS: Windows 10

**Comment by manutalcual** [comment]
Yes. I know. This is a known issue. I didn't have the time to investigate. I have a workaround, and because I don't have too much time, I decided to not fix it until I see someone is using the app.
Now I'm going to investigate that.
Until I fix this, what I do is to click on the "show desktop" corner, and when all windows are hidden, I click the app.
Also you have to select the "Get windows" each time you what to save their position. So in you example:

1. Move and maximize
2. Get windows
3. Save config

As said, I'm going to investigate that issue.

**Comment by manutalcual** [comment]
Ok. I think it is solved. The fix works on my laptop.
Try the new binaries (if you aren't compiling) and tell me if you have any problem.
BTW, the bin.zip in bin directory has now the exe and the dlls.

**Comment by zoidy** [comment]
Bug is fixed now. You're right that I missed the Get Windows part in my steps. I have a question about that but I will open a separate issue
